name: example-environment
channels:
  - conda-forge
dependencies:
  - python
  - numpy
  - graphviz
  - tensorflow
  - pip:
    - jupyter-tensorboard
    - keras
    - pandas
    - matplotlib
    - seaborn
    - scipy
    - sklearn
    - datetime
    - plotly
    - opencv-python
    
 
