name: example-environment
channels:
  - conda-forge
dependencies:
  - python
  - numpy
  - graphviz
  - tensorflow
  - datetime
  - pip:
    - jupyter-tensorboard
    - pandas
    - pickle
    - matplotlib
    - seaborn
    -scipy
 
